spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/donate?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&user=root&password=root
  application:
    name: donate
server:
  port: 8088
